# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bridgeit.com:
  peer0.importer.bridgeit.com:
  peer0.exporter.bridgeit.com:
  peer0.importerbank.bridgeit.com:
  peer0.insurance.bridgeit.com:
  peer0.custom.bridgeit.com:

networks:
  byfn:
services:
   ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-importer
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.importer.bridgeit.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.importer.bridgeit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/importer.bridgeit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerImporter
    networks:
      - byfn

  orderer.bridgeit.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bridgeit.com
    container_name: orderer.bridgeit.com
    networks:
      - byfn

  peer0.importer.bridgeit.com:
    container_name: peer0.importer.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importer.bridgeit.com
    networks:
      - byfn

  peer0.exporter.bridgeit.com:
    container_name: peer0.exporter.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporter.bridgeit.com
    networks:
      - byfn

  peer0.importerbank.bridgeit.com:
    container_name: peer0.importerbank.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importerbank.bridgeit.com
    networks:
      - byfn

  peer0.insurance.bridgeit.com:
    container_name: peer0.insurance.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insurance.bridgeit.com
    networks:
      - byfn

  peer0.custom.bridgeit.com:
    container_name: peer0.custom.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.custom.bridgeit.com
    networks:
      - byfn

