# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.bridgeit.com:
  peer0.importer.bridgeit.com:
  peer0.exporter.bridgeit.com:
  peer0.importerbank.bridgeit.com:
  peer0.insurance.bridgeit.com:
  peer0.custom.bridgeit.com:

networks:
  byfn:

services:

  orderer.bridgeit.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bridgeit.com
    container_name: orderer.bridgeit.com
    networks:
      - byfn

  peer0.importer.bridgeit.com:
    container_name: peer0.importer.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importer.bridgeit.com
    networks:
      - byfn

  peer0.exporter.bridgeit.com:
    container_name: peer0.exporter.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporter.bridgeit.com
    networks:
      - byfn

  peer0.importerbank.bridgeit.com:
    container_name: peer0.importerbank.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importerbank.bridgeit.com
    networks:
      - byfn

  peer0.insurance.bridgeit.com:
    container_name: peer0.insurance.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insurance.bridgeit.com
    networks:
      - byfn

  peer0.custom.bridgeit.com:
    container_name: peer0.custom.bridgeit.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.custom.bridgeit.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.importer.bridgeit.com:7051
      - CORE_PEER_LOCALMSPID=ImporterMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importer.bridgeit.com/peers/peer0.importer.bridgeit.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importer.bridgeit.com/peers/peer0.importer.bridgeit.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importer.bridgeit.com/peers/peer0.importer.bridgeit.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importer.bridgeit.com/users/Admin@importer.bridgeit.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.bridgeit.com
      - peer0.importer.bridgeit.com
      - peer0.exporter.bridgeit.com
      - peer0.importerbank.bridgeit.com
      - peer0.insurance.bridgeit.com
      - peer0.custom.bridgeit.com
    networks:
      - byfn

  ca.bridgeit.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.importer.bridgeit.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6121b129679bd2f9b52a58c89b08e647d0bef189b93b6e00b79238b3b5d3f07f_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.importer.bridgeit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6121b129679bd2f9b52a58c89b08e647d0bef189b93b6e00b79238b3b5d3f07f_sk -b admin:adminpw'
      - ./channel/crypto-config/peerOrganizations/importer.bridgeit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peer
    volumes:
      - ./crypto-config/peerOrganizations/importer.bridgeit.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - byfn